# Generated by Django 5.1.6 on 2025-06-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.category'),
        ),
    ]
