# Generated by Django 5.1.6 on 2025-07-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlisting_image_alter_bid_auction_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
