# Generated by Django 5.1.6 on 2025-07-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_comments', to='auctions.auctionlisting'),
        ),
    ]
